[workspace]
authors = ["Shantanu Singh <shsingh@broadinstitute.org>"]
channels = ["nvidia", "rapidsai", "conda-forge", "bioconda"]
name = "harmonyrsc"
platforms = ["linux-64"]
version = "0.1.0"
channel-priority = "disabled"
preview = ["pixi-build"]

[tasks]

[dependencies]
rapids = "25.8.*"
python = "3.13.*"
cuda-version = "12.9.*"
cudnn = "*"
cutensor = "*"
cusparselt = "*"
jupyterlab = "*"
pip = "*"
pre-commit = ">=4.3.0,<5"

[pypi-dependencies]
decoupler = "*"
omnipath = "*"
gdown = "*"
wget = "*"
rapids-singlecell = "*"
copairs-runner = { git = "https://github.com/broadinstitute/monorepo.git", subdirectory = "libs/copairs_runner", rev = "copairs-runner" }
